# ==========================================
# UNDERTALE THEME (LARGE & SPACED)
# ==========================================

background {
    monitor =
    color = rgb(0, 0, 0) # Pitch black
}

# Dialogue Prompt
label {
    monitor =
    text = <span letter_spacing="8192">* What is the password?</span>
    color = rgb(255, 255, 255)
    font_size = 64
    font_family = Determination Sans Web 
    position = 0, 120
    halign = center
    valign = center
}

# The Password Box
input-field {
    monitor =
    size = 600, 90
    outline_thickness = 6
    
    # Replaces default circles with asterisks
    dots_text_format = *
    dots_size = 0.35
    dots_spacing = 0.35
    dots_center = true
    
    outer_color = rgb(255, 255, 255)
    inner_color = rgb(0, 0, 0)
    font_color = rgb(255, 255, 255)
    font_family = Determination Sans Web
    
    fade_on_empty = false
    placeholder_text = 
    hide_input = false
    
    rounding = 0
    
    position = 0, -30
    halign = center
    valign = center

    check_color = rgb(255, 255, 255)    # Stops it from turning green/yellow when checking
    fail_text = You cannot give up just yet...
    fail_color = rgb(255, 255, 255) # Keeps the border white instead of turning red
}

# Error Message (Appears if you get it wrong)
#label {
#    monitor =
#    text = <span letter_spacing="5120">$FAIL, you must not give up!</span>
#    fail_text = <span letter_spacing="5120">$FAIL, you must not give up!</span>
#    color = rgb(255, 0, 0)     
#    font_size = 36
#    font_family = Determination Sans Web
#    position = 0, -160
#    halign = center
#    valign = center
#}

# ==========================================
# RETRO ANIMATIONS
# ==========================================
animations {
    enabled = false 
}
