$mainMod = SUPER
$terminal = ghostty
$fileManager = nautilus
$browser = librewolf
$menu = vicinae toggle

bind = $mainMod, F, exec, $browser
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, O, exec, flatpak run md.obsidian.Obsidian

bind = $mainMod, R, exec, $menu

# Entering copilot submap with 1s window
bind = SUPER SHIFT, F23, exec, sleep 1 && hyprctl dispatch submap reset
bind = SUPER SHIFT, F23, submap, lock_copilot_double_press

submap = lock_copilot_double_press

bind = , P, exec, ~/.config/hyprland/Scripts/switch_bg.sh
# Locking
bind=SUPER SHIFT, F23, exec, hyprlock


bind = , escape, submap, reset 

submap=reset
# Exited copilot submap


bind = ALT, Space, exec, $menu

# Not working god knows why
bind = , xf86poweroff , exec, systecmctl hibernate
